name: Terraform Apply

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v2

      - name: Install age
        run: sudo apt-get install -y age

      - uses: opentofu/setup-opentofu@v1

      - name: Decrypt secrets
        env:
          AGE_IDENTITY: ${{ secrets.AGE_IDENTITY }}
        run: just decrypt

      - name: Init
        run: just init

      - name: Apply
        run: just apply -auto-approve
