name: Terraform Apply

#on:
#  schedule:
#    - cron: "*/5 * * * *"
#      timezone: Asia/Kolkata
#  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: extractions/setup-just@v4

      - name: Install age
        run: sudo apt-get install -y age

      - uses: opentofu/setup-opentofu@v2

      - name: Decrypt secrets
        env:
          AGE_IDENTITY: ${{ secrets.AGE_IDENTITY }}
        run: just decrypt

      - name: Init
        run: just init

      - name: Apply
        run: just apply -auto-approve
